PL/Controllers/BenchedController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace PL.Controllers
{
    [Authorize(Roles ="Gerente")]
    public class BenchedController : Controller
    {
        private readonly HttpClient _httpClient;

        public BenchedController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Employee employee = new ML.Employee();
            employee.Employees = new List<object>();
            return View(employee);
        }

        [HttpPost]
        public async Task<IActionResult> GetAll(string Benched)
        {
            ML.Employee Employee = new ML.Employee();

            var response = await _httpClient.GetAsync("https://localhost:7180/api/Employee/benched?Benched="+ Benched);

            if (response.IsSuccessStatusCode)
            {
                var result = await response.Content.ReadFromJsonAsync<ML.Result>();

                if (result != null && result.Correct)
                {
                    Employee.Employees = new List<object>();

                    foreach (var item in result.Objects)
                    {
                        ML.Employee emp = JsonConvert.DeserializeObject<ML.Employee>(item.ToString());
                        Employee.Employees.Add(emp);
                    }
                }
                else
                {
                    ViewBag.Error = result?.ErrorMessage ?? "No se encontraron empleados benched.";
                }
            }
            else
            {
                ViewBag.Error = "Error al conectar con la API.";
            }

            return View(Employee);
        }
    }
}

PL/Views/Benched/GetAll.cshtml
@model ML.Employee
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center fw-bold">
            <h2>Empleados que han estado en Bench</h2>
        </div>
    </div>

    @using (Html.BeginForm("GetAll", "Benched", FormMethod.Post))
    {

        <div class="row">
            <div class="col-md-12">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Benched" id="flexRadioDefault1" value="Yes">
                    <label class="form-check-label" for="flexRadioDefault1">
                        Yes
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="Benched" id="flexRadioDefault2" value="No">
                    <label class="form-check-label" for="flexRadioDefault2">
                        No
                    </label>
                </div>
            </div>

            <div>
                <button class="btn btn-success">
                    Search
                </button>
            </div>
        </div>
    }

    <div class="row">
        <div class="col-md-12">
            @if (Model.Employees.Count > 0)
            {
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Año Ingreso</th>
                            <th>Ciudad</th>
                            <th>Educación</th>
                            <th>Género</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.Employee emp in Model.Employees)
                        {
                            <tr>
                                <td>@emp.IdEmployee</td>
                                <td>@emp.JoiningYear</td>
                                <td>@emp.City.Name</td>
                                <td>@emp.Education.Name</td>
                                <td>@emp.Gender.Name</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>

</div>